export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "inverse-surface": "#d4e4fa",
        "secondary-container": "#3131c0",
        "on-surface": "#d4e4fa",
        "surface-dim": "#051424",
        "surface": "#051424",
        "on-secondary-fixed": "#07006c",
        "surface-container-high": "#1c2b3c",
        "primary-container": "#0f172a",
        "error-container": "#93000a",
        "on-tertiary-fixed": "#00201c",
        "background": "#051424",
        "on-primary-container": "#798098",
        "tertiary-fixed": "#62fae3",
        "inverse-primary": "#565e74",
        "on-secondary-container": "#b0b2ff",
        "tertiary-container": "#001c18",
        "inverse-on-surface": "#233143",
        "on-tertiary": "#003731",
        "on-error": "#690005",
        "on-primary-fixed": "#131b2e",
        "on-surface-variant": "#c6c6cd",
        "outline-variant": "#45464d",
        "secondary": "#c0c1ff",
        "surface-variant": "#273647",
        "on-primary": "#283044",
        "on-error-container": "#ffdad6",
        "surface-tint": "#bec6e0",
        "error": "#ffb4ab",
        "on-secondary-fixed-variant": "#2f2ebe",
        "on-tertiary-fixed-variant": "#005047",
        "tertiary": "#3cddc7",
        "tertiary-fixed-dim": "#3cddc7",
        "primary": "#bec6e0",
        "surface-container": "#122131",
        "on-secondary": "#1000a9",
        "on-background": "#d4e4fa",
        "surface-container-lowest": "#010f1f",
        "primary-fixed": "#dae2fd",
        "on-primary-fixed-variant": "#3f465c",
        "secondary-fixed-dim": "#c0c1ff",
        "secondary-fixed": "#e1e0ff",
        "outline": "#909097",
        "surface-bright": "#2c3a4c",
        "on-tertiary-container": "#009182",
        "primary-fixed-dim": "#bec6e0",
        "surface-container-highest": "#273647",
        "surface-container-low": "#0d1c2d"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "gutter": "24px",
        "section-gap": "80px",
        "base": "8px",
        "container-max": "1200px",
        "card-padding": "32px"
      },
      fontFamily: {
        "h2": ["Space Grotesk"],
        "body-md": ["Inter"],
        "h3": ["Space Grotesk"],
        "code-inline": ["Space Grotesk"],
        "h1": ["Space Grotesk"],
        "label-caps": ["Space Grotesk"],
        "body-lg": ["Inter"]
      },
      fontSize: {
        "h2": ["32px", {"lineHeight": "1.2", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "body-md": ["16px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "h3": ["24px", {"lineHeight": "1.3", "fontWeight": "600"}],
        "code-inline": ["14px", {"lineHeight": "1.0", "fontWeight": "500"}],
        "h1": ["48px", {"lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "label-caps": ["12px", {"lineHeight": "1.0", "letterSpacing": "0.1em", "fontWeight": "700"}],
        "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "400"}]
      }
    },
  },
  plugins: [],
}
